name: check-build
on: [push, pull_request]
jobs:
  check-style:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup-Python
        uses: actions/setup-python@v1
      - name: Setup-Python-Extras
        run: | 
          pip install pycodestyle
      - name: Pycodestyle
        run: pycodestyle
