name: Fast-Checks
on: [pull_request]
jobs:
  FastChecks:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup-Python
        uses: actions/setup-python@v1
      - name: Install Python Tools
        run: | 
          pip install pycodestyle
          pip install pytest
          pip install pytest-cov
      - name: Install Rose
        run: |
          pip install -e .
      - name: Pycodestyle
        run: |
          pycodestyle
      - name: Install eslint
        run: |
          yarn
          yarn add eslint
          yarn run eslint --init
      - name: Eslint
        run: |
          yarn run eslint .
      - name: Rose Unit Tests
        run: |
          pytest --cov-append metomi/rose/tests/*
